#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively narrow down the list using fzf
# 3. Open the file in Vim


# rg --color=always --line-number --no-heading --smart-case "${*:-}" |

rg --files-with-matches --smart-case "${*:-}" |
    fzf --ansi \
    --height 100% \
    --delimiter : \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
    --bind 'enter:become(nvim {1} +{2})'

