#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively narrow down the list using fzf
# 3. Open the file in Vim

rg --color=always --line-number --no-heading --smart-case "${*:-}" |
    fzf --ansi \
    --height=50% \
    --delimiter : \
    --preview 'batcat --color=always {1} --highlight-line {2}' \
    --bind 'enter:become(nvim {1} +{2})'

